scorecard/Models/HomeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace scorecard.Models
{
    public class HomeIndexViewModel
    {
        public List<Group> Groups { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Update Message")]
        public string UpdateText { get; set; }

        [Display(Name = "Status")]
        public CriteriaState UpdateStatus { get; set; }

        [Display(Name = "Type")]
        public UpdateType UpdateType { get; set; }

        [Required]
        public int UpdateId { get; set; }
    }

    public class StatusUpdateViewModel
    {
        public IEnumerable<StatusUpdate> Updates { get; set; }

        public StatusUpdateViewModel(IEnumerable<StatusUpdate> updates)
        {
            this.Updates = updates;
        }
    }

    public class StatusUpdateViewFailedModel
    {
        public string Message { get; set; }
        public Exception Exception { get; set; }
    }
}

scorecard/Controllers/CriteriaController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using scorecard.Data;
using scorecard.Models;

namespace scorecard.Controllers
{
    [Authorize]
    public class CriteriaController : Controller
    {
        // POST: Criteria/UpdateStatus
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateStatus(HomeIndexViewModel model)
        {
            StatusUpdateViewFailedModel failureModel = new StatusUpdateViewFailedModel();
            failureModel.Message = "Unspecified Error.";

            if (ModelState.IsValid)
            {
                RAGContext context = new RAGContext();

                // get the current user
                string currentUserId = User.Identity.GetUserId();
//                ApplicationUser currentUser = context.Users.FirstOrDefault(x => x.Id == currentUserId);
                ApplicationUser currentUser = context.Users.Where(x => x.Id == currentUserId).FirstOrDefault();

                if (currentUser != null)
                {
                    // find the criteria we are updating
                    Criteria criteria = context.Criteria.Find(model.UpdateId);

                    if (criteria != null)
                    {
                        List<StatusUpdate> updates = new List<StatusUpdate>();

                        try
                        {
                            // if we have text and a state change, save both
                            if (model.UpdateStatus != criteria.State)
                            {
                                // save the state change
                                StatusUpdate state = new StatusUpdate();
                                state.Criteria = criteria;
                                state.StateFrom = criteria.State;
                                state.StateTo = model.UpdateStatus;
                                state.UpdateType = model.UpdateType;
                                state.User = currentUser;
                                state.Stamp = DateTime.Now;
                                criteria.Updates.Add(state);

                                criteria.State = model.UpdateStatus;

                                updates.Add(state);
                            }

                            // save the update text
                            StatusUpdate update = new StatusUpdate();
                            update.Criteria = criteria;
                            update.StateFrom = model.UpdateStatus;
                            update.StateTo = model.UpdateStatus;
                            update.UpdateType = model.UpdateType;
                            update.Text = model.UpdateText;
                            update.User = currentUser;
                            update.Stamp = DateTime.Now;
                            criteria.Updates.Add(update);

                            updates.Add(update);

                            context.SaveChanges();

                            // return view
                            StatusUpdateViewModel partialModel = new StatusUpdateViewModel(updates);
                            return PartialView("_StatusUpdatePartial", partialModel);
                        }
                        catch(Exception ex)
                        {
                            failureModel.Exception = ex;
                        }
                    }
                    else
                    {
                        failureModel.Message = "Unable to find Criteria.";
                    }
                }
                else
                {
                    failureModel.Message = "Unable to find ApplicationUser.";
                }
            }

            return PartialView("_StatusUpdateFailedPartial", failureModel);
        }
    }
}

scorecard/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using scorecard.Data;
using scorecard.Models;

namespace scorecard.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            RAGContext context = new RAGContext();

            HomeIndexViewModel model = new HomeIndexViewModel();
            model.Groups = context.Groups.ToList();
            
            return View(model);
        }
    }
}

scorecard/Views/Home/Index.cshtml
@using scorecard.Models
@model HomeIndexViewModel
@{
    ViewBag.Title = "Innovation Review – Draft Action Plan";
}

<div id="top-info">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Innovation Review – Draft Action Plan</h1>
                <p><strong>Please submit any comments or suggestions to <a href="mailto:innovation@gov.je">innovation@gov.je</a> no later than 2 december, or respond on twitter using <a href="https://twitter.com/intent/tweet?url=http://innovation.org.je&hashtags=jsyinnov&text=">#jsyinnov</a>.</strong></p>
                <p>The <a href="https://www.gov.je/InnovationReview" target="_blank">Jersey Innovation Review</a> is a major independent review which was carried out in 2015 to look at innovation in Jersey and the impact this has on the economy. The review was led by <a href="https://uk.linkedin.com/in/teraallas" target="_blank">Tera Allas</a>, a recognised expert in innovation policy who has advised the <a href="http://bit.ly/AllasUKInnov" target="_blank">UK</a> and the OECD on innovation strategy.</p>
                <p>Innovation is a key element of Jersey’s aim to improve productivity, and the 2015-2018 <a href="https://www.gov.je/Government/Pages/StatesReports.aspx?ReportID=1424" target="_blank">States Strategic Plan</a> sets out an aim to develop a strategy to enhance the Island’s innovation performance.</p>
                <p>This website has been set up to provide ongoing monitoring of the progress in meeting the recommendations of the Innovation Review. The <a href="https://en.wikipedia.org/wiki/Traffic_light_rating_system#Traffic_Light_RAG_and_BRAG_.28or_RAGB.29_Milestone_Project.2C_Program_and_Portfolio_status_reporting" target="_blank">RAG (Red Amber Green)</a> system is used for monitoring the progress on each of the recommendations.</p>
                <hr/>
                <div class="col-xs-12">
                    <div class="col-sm-2 box danger">Red</div>
                    <div class="col-sm-10"><p>The action is not on track to meet the completion date.</p></div>
                </div>
                <div class="col-xs-12">
                    <div class="col-sm-2 box warning">Amber</div>
                    <div class="col-sm-10"><p>Action is required to make sure the action is completed on time.</p></div>
                </div>
                <div class="col-xs-12">
                    <div class="col-sm-2 box success">Green</div>
                    <div class="col-sm-10"><p>The action is complete or is on track to be completed within the timescales.</p></div>
                </div>
                <div style="clear:left"><hr /></div>
                <p>
                    An implementation team has been formed within the States of Jersey to develop an action plan and lead on implementing the recommendations. The team includes officers from the Chief Minister’s Department and Economic Development Department, supported closely by a number of delivery partners both inside and outside government.</p>
                <p>Progress against the Action Plan will updated quarterly online at innovation.org.je and a report will be published annually to update on progress.</p>
                <p>
                    <br />
                    This website was designed by <a href="http://twitter.com/bearpig" target="_blank">@Html.Raw("@bearpig")</a> and built by <a href="http://twitter.com/mattcjsy">@Html.Raw("@mattcjsy")</a> as a community initiative.
                </p>
                <p>
                    The code, warts and all, is open source and can be viewed on <a href="https://github.com/innovationorgje/scorecard" target="_blank">GitHub</a>.
                </p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="rec_intro" id="status">
                <h2>Overview</h2>
                <p>You can click on any of these numbers to jump to the detailed status of that recommendation.</p>
                @foreach (var group in Model.Groups)
                {
                    foreach (var criteria in group.Criteria)
                    {
                        <a class="rec_square @criteria.CssClass" href="#rec-@criteria.ID">@criteria.Reference</a>
                    }

                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="recommendations">
                @foreach(var group in Model.Groups)
                {
                    <h2>@group.Title</h2>

                    foreach (var criteria in group.Criteria)
                    {
                        <div class="panel panel-@criteria.CssClass" id="rec-@criteria.ID">
                            <input type="hidden" class="current-status" value="@Convert.ToInt32(criteria.State)" />
                            <div class="panel-heading">
                                <h3 class="panel-title">@criteria.Title</h3>
                            </div>
                            <div id="panel-body-@criteria.ID" class="panel-body">
                                @criteria.Summary
                                @{
                        StatusUpdateViewModel m = new StatusUpdateViewModel(criteria.LatestUpdates);
                                }
                                @Html.Partial("_StatusUpdatePartial", m)
                                <div id="panel-placeholder-@criteria.ID"></div>
                            </div>
                            @if(User.Identity.IsAuthenticated)
                            {
                                <div class="panel-footer">
                                    <div class="update">
                                        <button id="upd-@criteria.ID" class="btn btn-primary btn-md update-criteria" type="button">Update</button>
                                    </div>
                                </div>
                            }
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>
@if(User.Identity.IsAuthenticated)
{
    <div class="panel-footer panel-footer-update">
        @using(Ajax.BeginForm("UpdateStatus", "Criteria", new AjaxOptions
        {
            InsertionMode = InsertionMode.InsertBefore,
            UpdateTargetId = "DYNAMIC",
            OnSuccess = "updateStatusSuccess",
            OnFailure = "showAjaxFormError"
        }))
    {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.UpdateId)

            <div class="form-group">
                <div class="row">
                    <div class="col-md-12">
                        @Html.LabelFor(m => m.UpdateText, new { @class = "control-label" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        @Html.TextAreaFor(m => m.UpdateText, new { @class = "form-control" })
                    </div>
                    <div class="col-md-10">
                        @Html.ValidationMessageFor(m => m.UpdateText, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                        @Html.LabelFor(m => m.UpdateStatus, new { @class = "control-label" })
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                        @Html.EnumDropDownListFor(m => m.UpdateStatus, new { @class = "form-control" })
                    </div>
                    <div class="col-xs-2 col-md-1">
                        @Html.LabelFor(m => m.UpdateType, new { @class = "control-label" })
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                        @Html.EnumDropDownListFor(m => m.UpdateType, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-2 col-md-1">
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3">
                    </div>
                </div>
                <div class="update">
                    <button class="btn btn-primary btn-md submit-update" type="submit"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Submit</button>
                    <button class="btn btn-default btn-md cancel-update" type="button">Cancel</button>
                </div>
            </div>
    }
    </div>
}